version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [db]
    # Mount the whole project so Alembic files persist on host
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-taskuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskpass}
      POSTGRES_DB: ${POSTGRES_DB:-taskdb}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
