"""add timestamps to tasks

Revision ID: c90dfaa32086
Revises: 914790be166b
Create Date: 2025-09-16 20:46:44.754452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90dfaa32086'
down_revision: Union[str, None] = '914790be166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_tasks_assignee_status', table_name='tasks')
    op.drop_index('ix_tasks_project_due_at', table_name='tasks')
    op.drop_index('ix_tasks_project_priority', table_name='tasks')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_project_created_at', 'tasks', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_created_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_index('ix_tasks_project_priority', 'tasks', ['project_id', 'priority'], unique=False)
    op.create_index('ix_tasks_project_due_at', 'tasks', ['project_id', 'due_at'], unique=False)
    op.create_index('ix_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
