name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_USER: taskuser
          POSTGRES_PASSWORD: taskpass
          POSTGRES_DB: taskdb
        options: >-
          --health-cmd="pg_isready -U taskuser -d taskdb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']

    env:
      APP_ENV: ci
      SECRET_KEY: change_me
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      REDIS_URL: redis://127.0.0.1:6379/0
      PYTHONUNBUFFERED: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && echo "postgres up" && break
            echo "waiting for postgres..." && sleep 2
          done

      - name: Alembic upgrade
        run: |
          alembic upgrade head

      - name: Run tests
        run: |
          pytest -q
